### ISSUE TITLE
VCF writing in simgenotype is very slow

### ISSUE THREAD

**Issue by s041629** [CAST-genomics/haptools#148]
After having run some pretty intense genotype simulations, it seems that the very slow step is writing out the VCF file (hours for 10k samples on chr19). For the next versions, will it be possible to output either vcf.gz or pgen files directly? 

Also, going higher than 10k samples may result in memory issues handling VCF files.

Thank you!

**Comment by aryarm** [comment]
hey @s041629 ! Thanks for creating this Github issue to help us keep track of this 🙏 

I think we initially had plans for reading/writing PGEN files in simgenotype (see https://github.com/CAST-genomics/haptools/issues/99#issuecomment-1251677768), but we decided to put it on pause until there came a point that we needed it. Perhaps this would be a good time to revisit the issue, @gymreklab and @mlamkin7 ?

I experimented with PGEN support a bit back in [PR #105](https://github.com/CAST-genomics/haptools/pull/105/files#diff-fb653a216b8c2a75af339eb1389c0660cfd6f9ba7702e9e713ab430dfef22295R220-R273), so we could start by adapting that code.

**Comment by s041629** [comment]
Is was just thinking for the future, thanks!

as input, I have always used vcf.gz without any issues. Writing directly to vcf.gz would speed things up quite a lot: with 10k individuals for one chromosome, the vcf.gz is 7gb and the vcf is > 40gb.

**Comment by aryarm** [comment]
Ah, ok. Here's an easy/temporary fix, then: just change the end of this line from `.vcf` to `.vcf.gz`:

https://github.com/CAST-genomics/haptools/blob/063b411302e4f299f02de82ad4040d2eb3fa8a61/haptools/sim_genotype.py#L107
