### ISSUE TITLE
Expanding population before simgenotype? 

### ISSUE THREAD

**Issue by KangchengHou** [CAST-genomics/haptools#242]
Hi,

Great software!

Is it needed to extend the genotype diversity before simulation admixture, as suggested by https://github.com/williamslab/admix-simu stating:

> To simulate N haplotypes, at most N+1 haplotypes from each source population will be needed. However, because ./simu-mix.pl is randomized, some runs will succeed in simulating N haplotypes even when fewer than N+1 haplotypes are available for each population.

In other words, do you think there are substantial quality differences of the simulated datasets across the following two procedures to simulate 10K African-European admixed individuals:
1.  start directly from 1,000 Genomes project raw data (total N ~ 2.5K)
2. start from a expanded dataset of 1,000 Genomes project (by first expanding the population into a larger one, e.g., N ~ 10K)

Thanks in advance,
Kangcheng

**Comment by mlamkin7** [comment]
Hello! Sorry for the delayed response. I am trying to get a better understanding of your question and was wondering what you mean by quality differences between using the different sizes of N? With a smaller pool in your reference dataset of N samples it's more likely you have less diversity in your resulting simulated population, but I'm not quite sure if there's anything else you're trying to convey.

**Comment by KangchengHou** [comment]
Thank you for the response. I wonder if you have recommendation on whether or not first expand the reference dataset (e.g., 1,000 Genomes) before applying `haptools simgenotype` if one want to perform similar simulation studies of https://academic.oup.com/bioinformatics/article/39/3/btad104/7058928 Fig. 1b.

**Comment by mlamkin7** [comment]
I would say if your resulting population is substationally larger than the reference it would be in your best interest to increase the amount in the reference, otherwise you would expect to see a lot of repeated haplotype blocks.
