### ISSUE TITLE
feat: add a command or parameter to allow merging of haplotype and genotype VCFs

### ISSUE THREAD

**Issue by aryarm** [CAST-genomics/haptools#82]
Or, at the very least, we could say something about the proper bcftools concat command in the docs

Internally, the way we would implement this:
- [ ] Add a `merge()` method on the Genotypes class that merges a set of genotypes with another set of genotypes.

**Comment by aryarm** [comment]
@wgonzalezrivera, can you paste the bcftools command that you used here?

**Comment by wgonzalezrivera** [comment]
`bcftools concat -a snps.vcf.gz haplotypes.vcf.gz -Oz -o new_file.vcf.gz`

**Comment by aryarm** [comment]
I just wanted to add a quick note that I've created a script to do this much more quickly with PGEN files!

https://github.com/CAST-genomics/haptools-paper/blob/main/workflow/scripts/merge.py

The script uses the haptools API

**Comment by aryarm** [comment]
added in #210 which was merged into main in #209
